"""empty message

Revision ID: 23a09400d464
Revises: 906a07d3bb31
Create Date: 2025-12-09 14:27:44.155685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a09400d464'
down_revision = '906a07d3bb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_tokens', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tokens')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('user_tokens')

    # ### end Alembic commands ###
