"""empty message

Revision ID: 2f94b49ef0fc
Revises: d538cdf34636
Create Date: 2025-09-26 17:41:56.847270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f94b49ef0fc'
down_revision = 'd538cdf34636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
