"""empty message

Revision ID: 61ce1b221668
Revises: 1daa7c358c5f
Create Date: 2025-07-25 11:15:43.736979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ce1b221668'
down_revision = '1daa7c358c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('all_members',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('all_members',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###
