"""empty message

Revision ID: 684c4816363e
Revises: 6ab0d62599b1
Create Date: 2025-10-14 01:48:11.078096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684c4816363e'
down_revision = '6ab0d62599b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('test_code')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_code', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
