"""empty message

Revision ID: 80092bcc494d
Revises: 
Create Date: 2025-09-07 20:14:24.553242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80092bcc494d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_code', sa.String(length=10), nullable=False),
    sa.Column('user_list', sa.String(length=300), nullable=False),
    sa.Column('author_name', sa.String(length=300), nullable=False),
    sa.Column('active_test', sa.Boolean(), nullable=True),
    sa.Column('all_members', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answers_per_question', sa.Integer(), nullable=True),
    sa.Column('test_code', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.String(length=100), nullable=False),
    sa.Column('image', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=100), nullable=False),
    sa.Column('answer_options', sa.String(length=300), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('date_complete', sa.String(), nullable=False),
    sa.Column('time_complete', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('test_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('quiz')
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('room')
    # ### end Alembic commands ###
