"""empty message

Revision ID: 856338190472
Revises: b0d207df08c4
Create Date: 2025-09-07 12:17:15.486452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856338190472'
down_revision = 'b0d207df08c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_confirmation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_confirmation', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
