"""empty message

Revision ID: 8c66ff396cd0
Revises: 4b97772bfeba
Create Date: 2025-05-20 21:01:26.308370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c66ff396cd0'
down_revision = '4b97772bfeba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_complete', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('date_complete')

    # ### end Alembic commands ###
