"""empty message

Revision ID: 93694f99b65b
Revises: 3d0ff573c3d3
Create Date: 2025-12-14 13:08:11.666111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93694f99b65b'
down_revision = '3d0ff573c3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
