"""empty message

Revision ID: 964640039901
Revises: d5d87a9c1da7
Create Date: 2025-05-25 20:46:50.583605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964640039901'
down_revision = 'd5d87a9c1da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
