"""empty message

Revision ID: a72217c78cf3
Revises: 5f81f611b2e3
Create Date: 2025-07-16 13:31:07.660000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72217c78cf3'
down_revision = '5f81f611b2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('all_members',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('all_members',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
