"""empty message

Revision ID: d00a0b7e4ad5
Revises: 90c2cdc187b2
Create Date: 2025-10-28 22:57:47.526895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00a0b7e4ad5'
down_revision = '90c2cdc187b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_classes')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson', sa.String(length=200), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('lesson')

    op.create_table('_alembic_tmp_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('class_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_date', sa.VARCHAR(length=100), nullable=False),
    sa.Column('class_color1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('class_color2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('max_user_count', sa.INTEGER(), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('lesson', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
